version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    networks:
      - laravel-network

  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www
      - "/run/desktop/mnt/host/c/fianarana/RappelReact(GESTION PROJET)/gestion-projet/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - laravel-network

  php-fpm:  # Add this service
    image: php:7.4-fpm
    volumes:
      - .:/var/www
    networks:
      - laravel-network

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: gestion_projet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel-network

volumes:
  db_data:

networks:
  laravel-network:
