version: "3.9"

services:
  # Backend Service (Laravel App)
  laravelapp:
    container_name: gestion_projet
    image: kevin/gestion_projet
    build: .  # Assuming the backend's Dockerfile is inside the 'back' directory
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  # Database Service (PostgreSQL)
  db:
    container_name: db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kevin
      POSTGRES_DB: gestion_projet
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  frontend:
    container_name: react_app
    build: ./front  
    ports:
      - "3000:3000"  
    volumes:
      - ./front:/app  
    environment:
      - CHOKIDAR_USEPOLLING=true  
    depends_on:
      - laravelapp  
    command: ["npm", "start"]  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  

volumes:
  pgdata: {}
